### ISSUE TITLE
Redundant if statement

### ISSUE THREAD

**Issue by sen1** [DeadMarshall/codecademy#3]
https://github.com/DeadMarshall/codecademy/blob/6f67a46034f5b5584c9f0e26fd028b57f73e80b6/bstinsonMurder%2BMystery.py#L171-L174

If the first check on `i not in frequency_table` fails then obviously `i in frequency_table` is true. So the second check is redundant. You can simply replace with else.

**Comment by DeadMarshall** [comment]
fixed
